; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Wrok"
#define MyAppVersion "1.6.1"
#define MyAppExeName MyAppName + ".exe"
#define MyAppPublisher "NASS e.K."
#define MyAppURL "https://www.nass-ek.de"
#define ProgramFiles GetEnv("ProgramFiles")

; Muss zu PublishDir in Properties\PublishProfiles\FolderProfile.pubxml passen.
; ACHTUNG: Das ist die PUBLISH-Ausgabe, nicht der normale Build. Vor dem
; Kompilieren des Setups muss in Visual Studio "Veroeffentlichen" gelaufen sein.
#define MyAppExeSource "bin\x64\Release\publish\" + MyAppExeName

; --- Schutz gegen veraltete oder fehlende Ausgaben ---------------------------
; Fruehere Setups haben stillschweigend eine alte Exe eingepackt, weil noch ein
; Rest eines aelteren Builds am gesuchten Ort lag. Beides wird jetzt abgefangen.

#if !FileExists(MyAppExeSource)
  #error Publish-Ausgabe fehlt. Bitte zuerst veroeffentlichen (Profil FolderProfile).
#endif

#define ExeFileVersion GetVersionNumbersString(MyAppExeSource)
#if ExeFileVersion != MyAppVersion + ".0"
  #pragma message "Exe-Dateiversion: " + ExeFileVersion + " / MyAppVersion: " + MyAppVersion
  #error Version der Exe passt nicht zu MyAppVersion. Publish veraltet oder AssemblyInfo.cs nicht angepasst?
#endif

[Setup]
AppId={{A5101A1F-25B3-4297-B279-A34FE3354AA3}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableDirPage=yes
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
; Explizit: Installation fuer alle Benutzer nach Program Files.
; Muss zu "Scope: machine" im WinGet-Manifest passen.
PrivilegesRequired=admin
; Interaktiv: eine laufende Instanz wird ueber [Code] (CloseRunningWrokIfNeeded)
; nach Rueckfrage aktiv beendet - siehe dort, ersetzt die fruehere AppMutex-Direktive,
; die nur passiv gewartet, aber nichts geschlossen hat.
; Still (WinGet-Hintergrund-Update): CloseApplications=force bleibt als Netz, falls
; eine Datei trotzdem noch gesperrt ist - ganz ohne Dialog, unveraendert wie bisher.
CloseApplications=force
RestartApplications=no
VersionInfoVersion={#MyAppVersion}
; Relative Pfade: Der Build bleibt damit in sich geschlossen und funktioniert
; unabhaengig von einem bestimmten Rechner oder Laufwerk.
LicenseFile=LICENSE.txt
ArchitecturesInstallIn64BitMode=x64compatible
ArchitecturesAllowed=x64compatible
OutputDir=bin\x64\Release
OutputBaseFilename={#MyAppName}-Setup-{#MyAppVersion}
SetupIconFile=Properties\wrok_black.ico
UninstallDisplayIcon={app}\{#MyAppExeName},0
DisableWelcomePage=False
; Aus wrok_white.ico erzeugt, damit der Assistent dasselbe Symbol zeigt wie
; Anwendung und Deinstallation.
WizardImageFile=Properties\wizard_large.bmp
WizardSmallImageFile=Properties\wizard_small.bmp
Compression=lzma
SolidCompression=yes
WizardStyle=modern
SignTool=Certum

[Languages]
Name: "de"; MessagesFile: "compiler:Languages\German.isl"
Name: "en"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "{#MyAppExeSource}"; DestDir: "{app}"; Flags: ignoreversion
Source: "Properties\wrok_black.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "Properties\wrok_white.ico"; DestDir: "{app}"; Flags: ignoreversion

[Tasks]
; BEWUSST OHNE "Flags: unchecked": Bei einer stillen Installation (WinGet) werden
; nur standardmaessig angehakte Tasks ausgefuehrt. Mit "unchecked" bekaeme kein
; einziger WinGet-Nutzer ein Desktopsymbol.
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; \
    GroupDescription: "{cm:AdditionalIcons}"

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; \
    IconFilename: "{app}\wrok_black.ico"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; \
    IconFilename: "{app}\wrok_black.ico"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#MyAppName}}"; \
    Flags: nowait postinstall skipifsilent

[Code]

const
  OldUninstallKey =
    'Software\Microsoft\Windows\CurrentVersion\Uninstall\{A5101A1F-25B3-4297-B279-A34FE3354AA3}_is1';
  WrokMutexName = 'Global\Wrok_SingleInstanceMutex';

{ Ersetzt die fruehere AppMutex-Direktive: die zeigte bei erkannter laufender
  Instanz nur einen Warte-Dialog ("bitte selbst schliessen, dann OK klicken"),
  schloss aber nichts selbst. Hier wird stattdessen aktiv nachgefragt und bei
  Zustimmung die laufende Instanz wirklich beendet.
  Im stillen Modus (WinGet-Hintergrund-Update) wird bewusst nichts gefragt -
  dafuer sorgt weiterhin CloseApplications=force beim Dateizugriff, ganz ohne
  Dialog, unveraendert wie bisher. }
function CloseRunningWrokIfNeeded(): Boolean;
var
  ResultCode: Integer;
  Elapsed: Integer;
begin
  Result := True;

  if WizardSilent() then
    Exit;

  if not CheckForMutexes(WrokMutexName) then
    Exit;

  if MsgBox('Wrok wird gerade ausgefuehrt und muss vor der Installation beendet werden.' + #13#10 +
            'Ungespeicherte Aenderungen (z. B. gerade bearbeitete Makros) gehen dabei verloren.' + #13#10#13#10 +
            'Jetzt schliessen und fortfahren?',
            mbConfirmation, MB_YESNO) = IDNO then
  begin
    Result := False;
    Exit;
  end;

  Exec('taskkill.exe', '/F /IM {#MyAppExeName}', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);

  { Kurz abwarten, bis der Mutex tatsaechlich freigegeben ist. }
  Elapsed := 0;
  while CheckForMutexes(WrokMutexName) and (Elapsed < 5000) do
  begin
    Sleep(200);
    Elapsed := Elapsed + 200;
  end;

  if CheckForMutexes(WrokMutexName) then
  begin
    MsgBox('Wrok konnte nicht automatisch beendet werden. Bitte schliesse es manuell und starte das Setup erneut.',
           mbError, MB_OK);
    Result := False;
  end;
end;

function InitializeSetup(): Boolean;
var
  UninstPath: string;
  ResultCode: Integer;
begin
  Result := True;

  if not CloseRunningWrokIfNeeded() then
  begin
    Result := False;
    Exit;
  end;

  { Pruefe zuerst HKLM, dann HKCU, ob eine alte Wrok-Installation existiert }
  if RegQueryStringValue(HKLM, OldUninstallKey, 'UninstallString', UninstPath) or
     RegQueryStringValue(HKCU, OldUninstallKey, 'UninstallString', UninstPath) then
  begin
    Log('Vorherige Wrok-Installation gefunden. Starte Deinstallation: ' + UninstPath);

    { Anfuehrungszeichen entfernen, damit wir eigene Parameter anhaengen koennen }
    UninstPath := RemoveQuotes(UninstPath);

    { Alte Version wirklich lautlos deinstallieren.
      /SILENT zeigt weiterhin ein Fortschrittsfenster und SW_SHOW blendet es ein –
      bei einer stillen WinGet-Installation darf nichts sichtbar werden. }
    if not Exec(UninstPath, '/VERYSILENT /SUPPRESSMSGBOXES /NORESTART', '', SW_HIDE,
                ewWaitUntilTerminated, ResultCode) then
    begin
      Log('Fehler beim Starten des Uninstallers. Rueckgabecode: ' + IntToStr(ResultCode));
      { Wenn du im Fehlerfall abbrechen willst, kommentiere die naechste Zeile aus: }
      { Result := False; }
    end
    else
    begin
      Log('Alte Wrok-Version deinstalliert. Rueckgabecode: ' + IntToStr(ResultCode));
    end;
  end
  else
  begin
    Log('Keine vorherige Wrok-Installation gefunden.');
  end;
end;
