; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Wrok"
#define MyAppVersion "1.0.0"
#define MyAppExeName MyAppName + ".exe"
#define MyAppPublisher "NASS e.K."
#define MyAppURL "https://www.nass-ek.de"
#define ProgramFiles GetEnv("ProgramFiles")

[Setup]
AppId={{A5101A1F-25B3-4297-B279-A34FE3354AA3}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableDirPage=yes
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
; Explizit: Installation fuer alle Benutzer nach Program Files.
; Muss zu "Scope: machine" im WinGet-Manifest passen.
PrivilegesRequired=admin
; Laufende Instanz beim Update automatisch schliessen, sonst sind die Dateien
; gesperrt und eine stille WinGet-Aktualisierung schlaegt fehl.
AppMutex=Global\Wrok_SingleInstanceMutex
CloseApplications=force
RestartApplications=no
VersionInfoVersion={#MyAppVersion}
LicenseFile=D:\Dokumente\gpl_de.txt
ArchitecturesInstallIn64BitMode=x64
ArchitecturesAllowed=x64
OutputDir=bin\x64\Release
OutputBaseFilename={#MyAppName}-Setup-{#MyAppVersion}
SetupIconFile=Properties\wrok_black.ico
UninstallDisplayIcon={app}\{#MyAppExeName},0
DisableWelcomePage=False
WizardImageFile=D:\Bilder\wz_nass-ek.bmp
WizardSmallImageFile=D:\Bilder\wz_leer_small.bmp
Compression=lzma
SolidCompression=yes
WizardStyle=modern
SignTool=Certum

[Languages]
Name: "de"; MessagesFile: "compiler:Languages\German.isl"
Name: "en"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "bin\Release\net8.0-windows\win-x64\publish\Wrok.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "Properties\wrok_black.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "Properties\wrok_white.ico"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}";
Name: "{autodesktop}\Wrok"; Filename: "{app}\Wrok.exe"; IconFilename: "{app}\wrok_black.ico"

[Run]
Filename: "{app}\Wrok.exe"; Description: "{cm:LaunchProgram,Wrok}"; Flags: nowait postinstall skipifsilent

[Code]

const
  OldUninstallKey =
    'Software\Microsoft\Windows\CurrentVersion\Uninstall\{A5101A1F-25B3-4297-B279-A34FE3354AA3}_is1';

function InitializeSetup(): Boolean;
var
  UninstPath: string;
  ResultCode: Integer;
begin
  Result := True;

  { Pr fe zuerst HKLM, dann HKCU, ob eine alte Wrok-Installation existiert }
  if RegQueryStringValue(HKLM, OldUninstallKey, 'UninstallString', UninstPath) or
     RegQueryStringValue(HKCU, OldUninstallKey, 'UninstallString', UninstPath) then
  begin
    Log('Vorherige Wrok-Installation gefunden. Starte Deinstallation: ' + UninstPath);

    { Anf hrungszeichen entfernen, damit wir eigene Parameter anh ngen k nnen }
    UninstPath := RemoveQuotes(UninstPath);

    { Alte Version wirklich lautlos deinstallieren.
      /SILENT zeigt weiterhin ein Fortschrittsfenster und SW_SHOW blendet es ein –
      bei einer stillen WinGet-Installation darf nichts sichtbar werden. }
    if not Exec(UninstPath, '/VERYSILENT /SUPPRESSMSGBOXES /NORESTART', '', SW_HIDE,
                ewWaitUntilTerminated, ResultCode) then
    begin
      Log('Fehler beim Starten des Uninstallers. R ckgabecode: ' + IntToStr(ResultCode));
      { Wenn du im Fehlerfall abbrechen willst, kommentiere die n chste Zeile aus: }
      { Result := False; }
    end
    else
    begin
      Log('Alte Wrok-Version deinstalliert. R ckgabecode: ' + IntToStr(ResultCode));
    end;
  end
  else
  begin
    Log('Keine vorherige Wrok-Installation gefunden.');
  end;
end;
