//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrok.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wrok.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die   {0} (deactivated) ähnelt.
        /// </summary>
        internal static string _0Deactivated {
            get {
                return ResourceManager.GetString("_0Deactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} seconds ähnelt.
        /// </summary>
        internal static string _0Seconds {
            get {
                return ResourceManager.GetString("_0Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ctrl+^ ähnelt.
        /// </summary>
        internal static string _Ctrl {
            get {
                return ResourceManager.GetString("_Ctrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About Wrok / Manual ähnelt.
        /// </summary>
        internal static string AboutWrok {
            get {
                return ResourceManager.GetString("AboutWrok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All data deleted ähnelt.
        /// </summary>
        internal static string AllDataDeleted {
            get {
                return ResourceManager.GetString("AllDataDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cache cleared ähnelt.
        /// </summary>
        internal static string CacheCleared {
            get {
                return ResourceManager.GetString("CacheCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cache has been deleted. ähnelt.
        /// </summary>
        internal static string CacheHasBeenDeleted {
            get {
                return ResourceManager.GetString("CacheHasBeenDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose what to be deleted: ähnelt.
        /// </summary>
        internal static string ChooseWhatToBeDeleted {
            get {
                return ResourceManager.GetString("ChooseWhatToBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear browsing data ähnelt.
        /// </summary>
        internal static string ClearBrowsingData {
            get {
                return ResourceManager.GetString("ClearBrowsingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear cache ähnelt.
        /// </summary>
        internal static string ClearCache {
            get {
                return ResourceManager.GetString("ClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ClearCacheAsync failed ähnelt.
        /// </summary>
        internal static string ClearCacheAsyncFailed {
            get {
                return ResourceManager.GetString("ClearCacheAsyncFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ClearCacheAsync failed:  ähnelt.
        /// </summary>
        internal static string ClearCacheFailed {
            get {
                return ResourceManager.GetString("ClearCacheFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear Cache only ähnelt.
        /// </summary>
        internal static string ClearCacheOnly {
            get {
                return ResourceManager.GetString("ClearCacheOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm ähnelt.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cookies, Login-Data and Settings deleted.
        ///You are logged out. ähnelt.
        /// </summary>
        internal static string CookiesLoginDataAndSettingsDeletedNYouAreLoggedOut {
            get {
                return ResourceManager.GetString("CookiesLoginDataAndSettingsDeletedNYouAreLoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Couldn&apos;t open link to GitHub: {0} ähnelt.
        /// </summary>
        internal static string CouldnTOpenLinkToGitHub0 {
            get {
                return ResourceManager.GetString("CouldnTOpenLinkToGitHub0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ctrl ähnelt.
        /// </summary>
        internal static string Ctrl {
            get {
                return ResourceManager.GetString("Ctrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ctrl+{0} ähnelt.
        /// </summary>
        internal static string Ctrl0 {
            get {
                return ResourceManager.GetString("Ctrl0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete all ähnelt.
        /// </summary>
        internal static string DeleteAll {
            get {
                return ResourceManager.GetString("DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete cache ähnelt.
        /// </summary>
        internal static string DeleteCache {
            get {
                return ResourceManager.GetString("DeleteCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete favorites ähnelt.
        /// </summary>
        internal static string DeleteFavorites {
            get {
                return ResourceManager.GetString("DeleteFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete macro? ähnelt.
        /// </summary>
        internal static string DeleteMacro {
            get {
                return ResourceManager.GetString("DeleteMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit macro ähnelt.
        /// </summary>
        internal static string EditMacro {
            get {
                return ResourceManager.GetString("EditMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EditMacroAndSave failed: {0} ähnelt.
        /// </summary>
        internal static string EditMacroAndSaveFailed0 {
            get {
                return ResourceManager.GetString("EditMacroAndSaveFailed0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit with right click. Run with {0}
        /// ähnelt.
        /// </summary>
        internal static string EditWithRightClickRunWith0 {
            get {
                return ResourceManager.GetString("EditWithRightClickRunWith0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while deleting cache: ähnelt.
        /// </summary>
        internal static string ErrorWhileDeletingCache {
            get {
                return ResourceManager.GetString("ErrorWhileDeletingCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while deleting cache:
        ///{0} ähnelt.
        /// </summary>
        internal static string ErrorWhileDeletingCacheN0 {
            get {
                return ResourceManager.GetString("ErrorWhileDeletingCacheN0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inaktivity ähnelt.
        /// </summary>
        internal static string Inaktivity {
            get {
                return ResourceManager.GetString("Inaktivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Left-click sends and submits.
        ///Shift+Click sends without Enter. ähnelt.
        /// </summary>
        internal static string LeftClickSendsAndSubmitsShiftClickSendsWithoutEnter {
            get {
                return ResourceManager.GetString("LeftClickSendsAndSubmitsShiftClickSendsWithoutEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Link couldn&apos;t be  oepened. ähnelt.
        /// </summary>
        internal static string LinkCouldnTBeOepened {
            get {
                return ResourceManager.GetString("LinkCouldnTBeOepened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Macro {0} ähnelt.
        /// </summary>
        internal static string Macro0 {
            get {
                return ResourceManager.GetString("Macro0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Macro click send failed: {0} ähnelt.
        /// </summary>
        internal static string MacroClickSendFailed0 {
            get {
                return ResourceManager.GetString("MacroClickSendFailed0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Macros
        ///- Edit: Right-click on a macro in the tray menu -&gt; Edit.
        ///- Send via menu: Left-click on a macro to insert the text and send it (Send+Enter).
        ///- Send without Enter: Left-click + Shift (or Alt) sends the text WITHOUT pressing Enter.
        ///- Hotkeys: Ctrl+1 .. Ctrl+5 send the respective macro. By default, Enter is sent after pasting (as with left-clicking).
        ///  Hold Shift or Alt while pressing the hotkey to suppress Enter.
        ///
        ///Boss-Key
        ///- To minimize the window press Strg+Tab.
        ///
        ///Clear cache
        ///- Tray menu → ‘ [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string MacroHelp {
            get {
                return ResourceManager.GetString("MacroHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Macros ähnelt.
        /// </summary>
        internal static string Macros {
            get {
                return ResourceManager.GetString("Macros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manual ähnelt.
        /// </summary>
        internal static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New macro ähnelt.
        /// </summary>
        internal static string NewMacro {
            get {
                return ResourceManager.GetString("NewMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Macro... ähnelt.
        /// </summary>
        internal static string NewMacroMenuItem {
            get {
                return ResourceManager.GetString("NewMacroMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nonet {
            get {
                object obj = ResourceManager.GetObject("nonet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parsing clickScript result failed: {0} ähnelt.
        /// </summary>
        internal static string ParsingClickScriptResultFailed0 {
            get {
                return ResourceManager.GetString("ParsingClickScriptResultFailed0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Personality ähnelt.
        /// </summary>
        internal static string Personality {
            get {
                return ResourceManager.GetString("Personality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pictures, scripts and other data deleted.
        ///You are still logged in. ähnelt.
        /// </summary>
        internal static string PicturesScriptsAndOtherDataDeletedNYouAreStillLoggedIn {
            get {
                return ResourceManager.GetString("PicturesScriptsAndOtherDataDeletedNYouAreStillLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reload window ähnelt.
        /// </summary>
        internal static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SaveMacros failed: {0} ähnelt.
        /// </summary>
        internal static string SaveMacrosFailed0 {
            get {
                return ResourceManager.GetString("SaveMacrosFailed0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send ähnelt.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send + Enter ähnelt.
        /// </summary>
        internal static string SendEnter {
            get {
                return ResourceManager.GetString("SendEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SendTextToWebViewAsync: clickScript result={0} ähnelt.
        /// </summary>
        internal static string SendTextToWebViewAsyncClickScriptResult0 {
            get {
                return ResourceManager.GetString("SendTextToWebViewAsyncClickScriptResult0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SendTextToWebViewAsync: click succeeded, returning. ähnelt.
        /// </summary>
        internal static string SendTextToWebViewAsyncClickSucceededReturning {
            get {
                return ResourceManager.GetString("SendTextToWebViewAsyncClickSucceededReturning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SendTextToWebViewAsync: jsSucceeded true, returning (no click). ähnelt.
        /// </summary>
        internal static string SendTextToWebViewAsyncJsSucceededTrueReturningNoClick {
            get {
                return ResourceManager.GetString("SendTextToWebViewAsyncJsSucceededTrueReturningNoClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die +Shift ähnelt.
        /// </summary>
        internal static string Shift {
            get {
                return ResourceManager.GetString("Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show window ähnelt.
        /// </summary>
        internal static string ShowWindow {
            get {
                return ResourceManager.GetString("ShowWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speech mode activated ähnelt.
        /// </summary>
        internal static string SpeechModeActivated {
            get {
                return ResourceManager.GetString("SpeechModeActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speech mode button not found ähnelt.
        /// </summary>
        internal static string SpeechModeButtonNotFound {
            get {
                return ResourceManager.GetString("SpeechModeButtonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown version ähnelt.
        /// </summary>
        internal static string UnknownVersion {
            get {
                return ResourceManager.GetString("UnknownVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WebView2 is not initialized yet. ähnelt.
        /// </summary>
        internal static string WebView2IsNotInitializedYet {
            get {
                return ResourceManager.GetString("WebView2IsNotInitializedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WebView2 not initialized yet. ähnelt.
        /// </summary>
        internal static string WebView2NotInitializedYet {
            get {
                return ResourceManager.GetString("WebView2NotInitializedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon wrok_black {
            get {
                object obj = ResourceManager.GetObject("wrok_black", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon wrok_white {
            get {
                object obj = ResourceManager.GetObject("wrok_white", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wrok - click to open ähnelt.
        /// </summary>
        internal static string WrokClickToOpen {
            get {
                return ResourceManager.GetString("WrokClickToOpen", resourceCulture);
            }
        }
    }
}
